check params first

diff --git a/azure-pipelines.yaml b/azure-pipelines.yaml
--- a/azure-pipelines.yaml
+++ b/azure-pipelines.yaml
@@ -45,10 +45,9 @@ jobs:
       InMemory:
         PersistentStores: ''
         kvUri: ''
-      ${{ if $[dependencies.infrastructure.outputs['pulumi.kvUri'] ] }}:
-        Persistent:
-          PersistentStores: 'true'
-          kvUri: $[ dependencies.infrastructure.outputs['pulumi.kvUri'] ]
+      Persistent:
+        PersistentStores: 'true'
+        kvUri: $[ dependencies.infrastructure.outputs['pulumi.kvUri'] ]
     maxParallel: 2
   condition: succeeded()
   pool:
@@ -60,6 +59,14 @@ jobs:
     buildConfiguration: 'Release'
 
   steps:
+
+  - script: |
+      if [ ! -z $(PersistentStores) ] && [ -z $(kvUri) ] ;
+        then
+              echo "PersistentStores is set, with no kvUri. Exiting with error"
+              exit 1
+        fi
+    displayName: Check params set correctly
 
   - script: dotnet build --configuration $(buildConfiguration)
     workingDirectory: apps
